### ISSUE TITLE
Do not rely on external repositories

### ISSUE THREAD

**Issue by cClaude** [YannCaron/Game4Kids#111]
Specially true if it refer to a branch like:
```javascript
  var script = document.createElement('script');
  script.setAttribute('src', 'https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js');
  document.head.appendChild(script);
```

**Comment by YannCaron** [comment]
I don't understand this issue !

**Comment by YannCaron** [comment]
I saw ! It is on the index.js file. I have just copied this part from Google blockly workspace generator.
To be fixed !

**Comment by YannCaron** [comment]
To keep off-line availability feature, Prettify was temporary copied to local directory ans modified with local paths as well.
Find better solution in future.
